### ISSUE TITLE
Button is no longer responsive

### ISSUE THREAD

**Issue by DrWiFi** [chrisjbrown/my-names-jeff#2]
Hello,
I am currently having an issue where clicking on the button to bring up the menu is no longer responding.
I tried creating a new game with just this module and Monks Enhanced Journal on 11.315 with both Chrome and Firefox.
Nothing is showing in the console when clicking on the button.

**Comment by chrisjbrown** [comment]
Was this module working for you before?
When clicking on the person icon, does it then render the actor types. Dragon, dwarf, halfling, etc?
Clicking one of these types you should see that the token name is updated based on your selection

**Comment by DrWiFi** [comment]
Hello,
Yes it was working prior. I am not sure what changed.
Clicking on the person icon does not pop up anything.

**Comment by chrisjbrown** [comment]
Thanks. I was able to reproduce the issue and just pushed a fix. Please try updating the module and trying again.

**Comment by DrWiFi** [comment]
That fixed it, thank you!

**Comment by chrisjbrown** [comment]
> That fixed it, thank you!

Excellent! Thanks for reporting the issue
