### ISSUE TITLE
Version 12 compatibility?

### ISSUE THREAD

**Issue by DrWiFi** [chrisjbrown/my-names-jeff#4]
Do you have plans for this to be updated to version 12?
The button is missing from tokens and I'm getting a console error:
<img width="1082" alt="Screenshot 2024-07-21 at 10 04 17 PM" src="https://github.com/user-attachments/assets/0b61bcd4-c8a9-4e37-b9cd-dae49388729c">

**Comment by DrWiFi** [comment]
Never mind, I'm apparently blind and did not notice the icon moved to the other side of the token.
I am still getting the console error though.
My players really like all the creatures having their own names, thank you for writing this.

**Comment by chrisjbrown** [comment]
> Never mind, I'm apparently blind and did not notice the icon moved to the other side of the token. I am still getting the console error though. My players really like all the creatures having their own names, thank you for writing this.

Thanks for opening an issue.
looks like v12 moved some things around. 
I published a new release that moves the icon back to the left column above the "cog" icon
and the error message in the console should not appear anymore
Glad you like the module!
